name: CI

on:
  schedule:
    - cron:  '0 4 1,15 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
      - name: CI
        run: make ci
      - name: Publish build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
