name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
      - name: CI
        run: make build/test-image ci
      - name: Publish build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
