name: Control

on:
  schedule:
    - cron:  '0 3 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
      - name: Preparing Test Image
        run: make build/test-image
      - name: Control Tests
        run: make test-real
      - name: Publish artifacts
        if: failed()
        uses: actions/upload-artifact@v1
        with:
          name: Error
          path: ./build/error.txt
