name: Control

on:
  schedule:
    - cron:  '0 3 1,15 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
      - name: Control
        run: make build/test-image test-real
