name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install make -y
          git clone https://github.com/estesp/manifest-tool && cd manifest-tool && git checkout v0.9.0 && sudo make && sudo make install && cd .. && rm -Rf manifest-tool
          docker run --rm --privileged multiarch/qemu-user-static:register
          sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
      - name: Build image
          run: make build
