name: Tests

on:
  schedule:
    - cron:  '0 5 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
      - name: Preparing Image
        run: make build/test-image
      - name: Tests
        run: make test
      - name: Publish Tests artifacts
        if: failed()
        uses: actions/upload-artifact@v1
        with:
          name: Tests
          path: ./build/junit.xml
